### ISSUE TITLE
Ruby bundle will not install in ubuntu 17.04

### ISSUE THREAD

**Issue by guysoft** [kochd/electricsheep-hd-client#1]
Hey, When I do ``bundle install``
I get:

```
electricsheep-hd-client$ bundle install
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.13.6/exe/bundle (LoadError)
        from /usr/local/bin/bundle:23:in `<main>```

What am I missing?

**Comment by kochd** [comment]
I dont know. Looks like a distributor problem to me.
You could try installing the official bundler version instead the ubuntu one: 
`gem install bundler` then do `bundle install` again.

**Comment by guysoft** [comment]
Ok that solves it. I guess ``sudo gem install bundler`` was a better way to do it than apt-get
