### ISSUE TITLE
two databases?

### ISSUE THREAD

**Issue by Ghitim** [kochd/electricsheep-hd-client#100]
is there two databases we switch between or something? i seem to have a different api key on each. is this to be expected? same user/pass, different highscores, different api keys

**Comment by kochd** [comment]
Not sure why you think that is:

If you are kima(...)dios.com you are registered with two accounts.
Your client stored your api key in the api.key file.
Maybe you are running two installations with either one of those different api keys?

**Comment by Ghitim** [comment]
I'm registered with ghit(...)dios.com, on both set's of data, both API key's. they're def different, nearly every-time the site goes down (like right now) when it comes back up it switches API keys. it's a different high score, I've got two point values that i've added points to separately over the time I've been here. i log in each time i need to using the same username password combo to get the "new" api key to enter it. then it connects and works as expected. rinse repeat.

**Comment by Ghitim** [comment]
weird! glad i could help expose it for you to fix :D stupid isp! it happens. no worries :) thank you so much for setting all this up and providing it and etc! you're great, glad to be apart of it.

**Comment by kotenok2000** [comment]
Now i can't connect my client to server
https://github.com/kochd/electricsheep-hd-client/issues/101
