### ISSUE TITLE
I can't connect to server.

### ISSUE THREAD

**Issue by kotenok2000** [kochd/electricsheep-hd-client#101]
I see this in console
[Текстовый документ.txt](https://github.com/kochd/electricsheep-hd-client/files/11709095/default.txt)

**Comment by Ghitim** [comment]
i am also having issues connecting, the console says server response: 500, internal server error. 
since yesterday when the database issue was resolved no frames rendered have been registered to highscore and no FPM registered. my score has gone up a little since then tho (maybe confirming frame?)

**Comment by Ghitim** [comment]
update: everything above seems to have been resolved

**Comment by AstraLuma** [comment]
This seems to be back?
