### ISSUE TITLE
Bundled mpv client cannot render .webm on windows

### ISSUE THREAD

**Issue by arman68** [kochd/electricsheep-hd-client#15]
The bundled mpv client reads and processes the .webm files, but renders them as a black screen. I suspect the following source was used:
https://mpv.srsfckn.biz/

More recent builds work fine, and can be found at:
https://sourceforge.net/projects/mpv-player-windows/

Tested successfully.
Please update installer accordingly.

**Comment by kochd** [comment]
@GeorgeHahn @earsneyes is play working for you guys on windows? I tested the installer on Windows 7 and it worked for me.

**Comment by kochd** [comment]
I packaged a new installer with the latest mpv build. Please check if it works for you @arman68

**Comment by arman68** [comment]
Yes it is working with the new installer, on windows 10. The bundled version of mpv renders the .webm files properly. Thank you.
