### ISSUE TITLE
Solving PoW takes too long.

### ISSUE THREAD

**Issue by withthelemons** [kochd/electricsheep-hd-client#16]
On my system (AMD 1950X, Windows 10), solving PoW takes about 60 seconds, while rendering the frame takes 33 seconds. I find it a bit wasteful that only 1/3 of time is spent on actually doing the work and rest is spent on calculating the PoW hash.

Is it possible to optimize the hashing or make it easier?

**Comment by kochd** [comment]
Hi @withthelemons ,
I'm planing to make pow easier for people who have proven to be trustworthy. This is currently not implemented.

**Comment by kochd** [comment]
Highly trusted members will get a easier pow to solve now.
