### ISSUE TITLE
Windows Screensaver support?

### ISSUE THREAD

**Issue by Plloi** [kochd/electricsheep-hd-client#19]
Any plan to support a windows native screensaver?

**Comment by kochd** [comment]
For my self the interest is near to zero. However if i am really really bored someday there is a chance i will implement it. Actually I was hoping for someone who has figured out how to develop software using windows to do the job for the community. I was reading the documentation and it doesn't seam that hard.

**Comment by slester87** [comment]
If I get a chance, I'll throw some time at this.
If someone wants to beat me to it, so far I've found [this tutorial for writing a Windows screen saver in C#](https://www.harding.edu/fmccown/screensaver/screensaver.html)

**Comment by StanekO** [comment]
Hi, I have been a shor time testing: [https://superuser.com/questions/538146/run-a-batch-cmd-upon-screensaver](url). "RunSaver" is not working properrly. Download "Screen Launcher" and save to "C:\Windows\". I dont know, if software is safe (checked only by ESET antivirus). And set target like: "play_windows.cmd" or "screansaver.bat". Now is working, not perfect like .scr, (you shud use ESC to end playng) but it works.
screansaver.bat: 
```
cd %~p0
START daemon_windows.cmd /LOW
CALL play_windows.cmd
TASKKILL /F  /IM "cmd.exe" /FI "WINDOWTITLE eq Electric Sheep HD daemon"  /T
```

**Comment by kochd** [comment]
I got working code from the libmpv examples.
Compiled and tested on linux: works... easy.
Compiling simple things for windows is just a pain in the a**. Cant figure it out.
If anybody is more into this than me and wants to give it a try:

```C

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#include <mpv/client.h>

static inline void check_error(int status)
{
    if (status < 0) {
        printf("mpv API error: %s\n", mpv_error_string(status));
        exit(1);
    }
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("pass a single media file as argument\n");
        return 1;
    }

    mpv_handle *ctx = mpv_create();
    if (!ctx) {
        printf("failed creating context\n");
        return 1;
    }

    // Enable default key bindings, so the user can actually interact with
    // the player (and e.g. close the window).
    check_error(mpv_set_option_string(ctx, "input-default-bindings", "yes"));
    mpv_set_option_string(ctx, "input-vo-keyboard", "yes");
    int val = 1;
    check_error(mpv_set_option(ctx, "osc", MPV_FORMAT_FLAG, &val));

    // Done setting up options.
    check_error(mpv_initialize(ctx));

    // Play this file.
    const char *cmd[] = {"loadfile", argv[1], NULL};
    check_error(mpv_command(ctx, cmd));

    // Let it play, and wait until the user quits.
    while (1) {
        mpv_event *event = mpv_wait_event(ctx, 10000);
        printf("event: %s\n", mpv_event_name(event->event_id));
        if (event->event_id == MPV_EVENT_SHUTDOWN)
            break;
    }

    mpv_terminate_destroy(ctx);
    return 0;
}
```
Run
compiled.exe $PATH_TO_M3U_PLAYLIST.

**Comment by kochd** [comment]
[test.zip](https://github.com/kochd/electricsheep-hd-client/files/3636236/test.zip)

Testers needed. Extract both to system32, open screensaver settings, select eshd.

Known bugs:
Opens supposed preview as fullscreen

**Comment by kochd** [comment]
@StanekO @earsneyes testers needed :)

**Comment by earsneyes** [comment]
If i try to preview it opens a window but closes so fast i could'nt read the output.
renaming to eshd.exe and executing it just says: "fopen failed:"

**Comment by kochd** [comment]
Do you have HKLM\Software\Electric Sheep HD\Settings\InstallPath string in the registry? And does it point to the correct installation path?

**Comment by earsneyes** [comment]
I did just installed electricsheep on my office machine with the installer. Couldnt find the registry entry but probably just do dumb to find it.. will need to report back later in the evening.

**Comment by kochd** [comment]
![Unbenannt](https://user-images.githubusercontent.com/1825660/65336440-a92fcb00-dbc6-11e9-81fb-fae65be7f5b6.png)

**Comment by kochd** [comment]
Ah... if you just installed it... there are no sequences and play was never executed ? Then this wont works as there are not sequences which play could write into the m3u playlist

**Comment by kochd** [comment]
Source for the scr build: https://github.com/kochd/electricsheep-hd-windows-scr

**Comment by earsneyes** [comment]
I have let run the just installed version a short time, copied over a few sheep files from my fileserver and let play do its thing. 
screensaver still did'nt start and executing the .exe tells still the same "fopen failed".

**Comment by kochd** [comment]
Ooops my fault. The installer actually does not create it in the 64bit path but in the 32bit path (SOFTWARE\Wow6432Node\...). I must have created mine by hand. Please create it by hand for now. I'll need to build a new installer.

**Comment by kochd** [comment]
New installer which correctly creates the registry node:
https://github.com/kochd/electricsheep-hd-client/releases/latest

**Comment by earsneyes** [comment]
It works now.

**Comment by StanekO** [comment]
Great...
I think: [https://github.com/kochd/electricsheep-hd-windows-scr/blob/ac05572dda4784f3e501608445fd74eaaf6c3aa5/eshd.c#L85](url)
`check_error(mpv_set_option_string(ctx, "stop-screensaver", "no")); `
should be YES

**Comment by kochd** [comment]
You need to see this from a media players viewpoint:
<pre>
              Turns off the screensaver (or screen blanker and similar mechanisms) at startup and turns it on again  on  exit  (de‐
              fault: yes). The screensaver is always re-enabled when the player is paused.
</pre>
When playing media files with mpv its annoying when the screensaver starts but as mpv itself is configured as the screensaver here it would probably prevent itself from running.
I didn't test it but that's the save option when using it as the screensaver.

**Comment by kochd** [comment]
The screensaver is shipped with the new windows installer now and got the feature the call play to generate an updated m3u playlist. 
Is it working as expected? I can only test it in a VM which decodes videos poorly at 0.something fps.

**Comment by StanekO** [comment]
> You need to see this from a media players viewpoint:
> 
>               Turns off the screensaver (or screen blanker and similar mechanisms) at startup and turns it on again  on  exit  (de‐
>               fault: yes). The screensaver is always re-enabled when the player is paused.
> When playing media files with mpv its annoying when the screensaver starts but as mpv itself is configured as the screensaver here it would probably prevent itself from running.
> I didn't test it but that's the save option when using it as the screensaver.

I have tested on Windows, and:
```
disable screensaver = YES = stop-screensaver (default)
disable (disable screensaver) = NO = no-stop-screensaver

Every flag option has a no-flag counterpart, e.g. the opposite of the --fs option is --no-fs. --fs=yes is same as --fs, --fs=no is the same as --no-fs.
```

I have this problem with "windows_screensaver.cmd:" and now, i find, it can be solved by this parameter.
eshd.scr is working even with "no-stop-screensaver", but PLAY need to be set YES, i saw, you have already implement this option.. Tx.

**Comment by kochd** [comment]
Yes on windows your screensaver would start when you just run play. The thing is that linux uses play directly as the screensaver (not like windows where this special binary compiled from C is needed). Therefore we cant use --stop-screensaver as the default because it might break functionality on linux even if its the better approach for windows. But as we have a proper windows screensaver now think this isn't a problem anymore as people could just use the screensaver instead of running play directly.

**Comment by kochd** [comment]
My windows development environment decided it would be great to stop booting and ignore every repairing approach. So I had to setup a new windows vm and now the SCR segfaults within mpv-1.dll.
Can anybody confirm that the current release is working and its just my VM which fails to start it?

**Comment by kochd** [comment]
<pre>
user@user-PC MINGW64 ~
$ gdb '/c/Users/user/Desktop/electricsheep-hd-windows-scr/build/Electric Sheep HD.scr'
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /c/Users/user/Desktop/electricsheep-hd-windows-scr/build/Electric Sheep HD.scr...done.
(gdb) set args /s
(gdb) run
Starting program: /c/Users/user/Desktop/electricsheep-hd-windows-scr/build/Electric Sheep HD.scr /s
[New Thread 912.0x810]

C:\msys64\home\user>title Electric Sheep HD daemon

C:\msys64\home\user>cd \Program Files (x86)\Electric Sheep HD\

C:\Program Files (x86)\Electric Sheep HD>set PATH=C:\Windows\system32;C:\Program Files (x86)\Electric Sheep HD\contrib\bin

C:\Program Files (x86)\Electric Sheep HD>ruby play --only-m3u   || pause
Got 3 parts
[New Thread 912.0xf48]
[New Thread 912.0xea0]
[New Thread 912.0xc4c]
[New Thread 912.0xef8]
[Thread 912.0xef8 exited with code 0]
[New Thread 912.0xe68]
[Thread 912.0xe68 exited with code 0]
[New Thread 912.0xb94]
[New Thread 912.0x214]
[Thread 912.0x214 exited with code 0]
[New Thread 912.0x35c]

Thread 9 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 912.0x35c]
0x000000006dc15af5 in ?? ()
   from /c/Users/user/Desktop/electricsheep-hd-windows-scr/build/mpv-1.dll
</pre>

**Comment by kochd** [comment]
Note to myself: Windows is a mess. Expect unexpected behavior when building software on it. 

If anything links to the pile of mess that windows API is without being compatible to that version of a "shared" library its shipping it will just silently segfault guiding you into the wrong direction: namely libmpv.

In that case a proper version of directX was missing to provide updated versions of d3dcompiler, libEGL and libGLES

**Comment by StanekO** [comment]
As you can see in original, they have at screensaver setup, so "to do list" in a future should be:

- setup directory to download sheets (daemon update?)
- enable/disable/delay renderings new sheets
- enable/disable download new sheets
- keep frames
- setup API key

It is good to see, you like windows development O:-) :-)

**Comment by kochd** [comment]
:smile:  i successfully avoided digging into it for over a year. We should probably implement some kind of config file which gets parsed for the options selected to make it cross platform and ship a simple GUI for windows which builds it.
Also: Forking the daemon in the background when the screensaver kicks in. This would be the classic electricsheep behavior.
So much stuff to do - so little time

**Comment by StanekO** [comment]
You knew, windows screensaver will give to you much more users...
You will get more CPU/GPU power -> less server space and more internet server traffic :-) And glory of success :-)

**Comment by StanekO** [comment]
It is possible to send signal from MPV to daemon, to be able voting at screensaver?

**Comment by kochd** [comment]
MPVs script-binding could be used to make api calls directly.
