### ISSUE TITLE
How to rename for compatibility with official client?

### ISSUE THREAD

**Issue by arman68** [kochd/electricsheep-hd-client#20]
Hi,

I am working on a raspberry pi build for this electricsheep-hd client. In a first phase, I using the official electricsheep client, for some testing. Later on, I am planning to switch to a hardware accelerated build using this client and generator.

For my testing, I cannot figure out how to properly rename the hd movies for re-use in the official build. Any clue?

**Comment by kochd** [comment]
Sorry i am not quite sure about this but there are multiple problems with your plan.
https://github.com/scottdraves/electricsheep/wiki/Protocol
Read #Filenames

Note that we use webm the they use mpeg/avi
Note that we have a sequential order.

Hope this helps. 

00244=$id=01994=01994.avi would translate to:
electricsheep.244.00065.01994_electricsheep.244.00065.01994.webm
where $id should be uniq over all files i believe. This would be a cycle where an edge would look like this 

00244=$id=01994=00066.avi
electricsheep.244.00065.01994_electricsheep.244.00066.00321.webm

>  I am working on a raspberry pi build for this electricsheep-hd client.

What do you mean by raspberry pi build? We use ruby and flam3 which both should work fine on arm cpus ?

**Comment by kochd** [comment]
I am closing this issue. If you have any further questions reopen it.
