### ISSUE TITLE
GPU reder

### ISSUE THREAD

**Issue by Rostislaved** [kochd/electricsheep-hd-client#24]
How to run gpu rendering? Daemon starts cpu by default

**Comment by HappyDagger** [comment]
use the flag --gpu to render using GPU.

**Comment by Rostislaved** [comment]
Does it work in windows? I changed daemon file like this:
title Electric Sheep HD daemon
cd %~p0
set PATH=%SYSTEMROOT%\system32;%cd%\contrib\bin
ruby daemon --gpu %* || pause
And it doesn't run

**Comment by kochd** [comment]
There is an separate Lnk for GPU rendering:
 https://github.com/kochd/electricsheep-hd-windows-installer/blob/master/setup.iss#L55

**Comment by kochd** [comment]
I am closing this because there was no further response from @Rostislaved

**Comment by kochd** [comment]
It's working see https://github.com/kochd/electricsheep-hd-client/issues/25#issuecomment-530440733

**Comment by kochd** [comment]
If you need further help you should provide some output of the client
