### ISSUE TITLE
How to donate ?

### ISSUE THREAD

**Issue by earsneyes** [kochd/electricsheep-hd-client#27]
Hi there,

i just got to it and played a little with the 4k sheeps and wanted to ask how to donate a few bucks ?

I went to https://liberapay.com/claw/donate but it seems the setup is incomplete so i cant donate right now.

Is there an other option ? paypal maybe ?

Cheers
Linus

**Comment by kochd** [comment]
Hey Linus,
Glad you are back :tada: 

I added a payment service to librepay. Thank you for your donation. Everything helps.
