### ISSUE TITLE
windows 10 install 

### ISSUE THREAD

**Issue by Mankeysocks** [kochd/electricsheep-hd-client#3]
C:\ELSHD\electricsheep-hd-client-master>ruby daemon    || pause
daemon:20:in ``': No such file or directory - which flam3-animate (Errno::ENOENT)
        from daemon:20:in `<main>'

**Comment by kochd** [comment]
Windows is not tested that much (yet). I'll have a look into this. You could try that Windows 10 Linux Subsystem thing.

Looks like the binary for flam3-animate is not added to your $PATH as which cant find it. 

https://github.com/kochd/electricsheep-hd-client/blob/master/daemon_windows.cmd#L2

I tested on Windows 7 a few years ago and it was working properly there. Cant tell i that a Windows 10 thing as i do not have any access to Windows 10.

**Comment by kochd** [comment]
Ah there we go. I think you did it wrong.
You need to place the folder named git+flam3+ruby inside the base not its contents.
