### ISSUE TITLE
Download only option enhancement?

### ISSUE THREAD

**Issue by earsneyes** [kochd/electricsheep-hd-client#30]
I had a go again with HD sheeps and must say that i am blown away by the beauty. so i did throw some workers on to the task.

Because i am unpatient i wanted to play as many clips i could and asked myself if decoupling the render task from the downloader with an option --nr --no-render "Do not download frames" could be implemented easy enough ?

That way i could put the player/TV (1080p) displayed in the office to use and play a long flock of sheeps and let the other machines do the work. 

I would then have an always envolving display of how this kind of repetitive mathematics and genetic algorithms based animation looks a like and we could use this installation as archive/seeder (P2P) as well at a later stage i guess :)

Anyway, the Full-HD sheeps are mindbending and beautyfull. especially the higher resolution ones. This already blows my mind with 1080p.

Cheers
Linus

**Comment by kochd** [comment]
Sounds easy but any /api/ request costs trust. So i need to think this thru:
If you would just leave it running requesting sequences (with or without download doesn't matter) all the time without submitting anything back you would end being banned after while with the current behavior

**Comment by earsneyes** [comment]
I am aware of this. My scenario would need some horespower all the time so the displaying device does not run dry.

**Comment by highdefractal** [comment]
couldn't you just share a drive from one of the rendering boxes to the display only box. no need to run the client on the display only machine

**Comment by kochd** [comment]
37828adb6542dfeeae4a292b0d3f1d6543296cdb implemented this. If there are no sheeps left it will sleep for an hour so the trust loss is not that immense.

**Comment by earsneyes** [comment]
@kochd thanks, i am running it now an will have an eye one it.
@highdefractal yes thats what i am doing most of the time but its not always feaseable because of a remote installation without the mounted fileserver or cloud access. If a p2p functionality is implemented it could serve as seed as well and add download bandwidth to the network.
