### ISSUE TITLE
RaspberryPi 4 -> 4K sheep display 

### ISSUE THREAD

**Issue by earsneyes** [kochd/electricsheep-hd-client#31]
I am want to play 4K sheeps on a big screen at some stage and planning to deploy a raspberrypi 4 for that purpose.

ElectricSheepPi https://github.com/guysoft/ElectricSheepPi was working for me in the past and thats why i want to test such solution with recent hardware and higher resolution now.

Also for the 4k sheeps i would love to get the most quality but can't reley on the rendered frames (saved locally) because i would miss frames right? I dont care too much about hd space usage but high bitrate/codec.

Anyone tried to run electricsheep-hd-client with rasbian or has some insights regarding running it on a Rpi4  with 4K branch / clips? Its early days for 4K playback on rpi4, i know. Thought i ask around here before going that direction.

Cheers
Linus

EDIT:  I tried it on a RPI4 and it only spit out garbage  / scrambled video right now. Will need to have a look the next days.

**Comment by kochd** [comment]
Hi Linus,

Absolutely nothing special to do. Just do the normal Linux installation as of: (https://github.com/kochd/electricsheep-hd-client#debian--ubuntu--). 
Also every compiled 3rd party software is available on raspberian (mpv, flam3, ruby, git).

**Comment by kochd** [comment]
Problem: AFAIK Raspberry has no HW-Acceleration for VP8/VP9 codecs. It will properly only perform with H264/H265. MPEG clearly the better codes but i am refusing to use it due to their problematic license. Open source needs a good royalty free codec which HW vendors cant ignore. I have high hopes in AV1.

**Comment by kochd** [comment]
https://en.wikipedia.org/wiki/VP9#Hardware_implementations

**Comment by earsneyes** [comment]
Bummer. VP9-Codec and Raspberrypi are not friends as it looks.

My Raspberry Pi 4 & Rpi2 both are unable to correctly play back 1080p videos encoded with vp8 and vp9. Disappointing to find this out as I had thought it would work.

**Comment by kochd** [comment]
I really dont want to support H265 officially but you could patch this with just a few lines of code.
daemon:
https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L328
after the rename
```ruby
system("ffmpeg -i '#{@movie_dir}/#{wanted}' '#{@movie_dir}/#{wanted.sub(/\.webm$/, '.mp4')}'")
```
This will encode a H264/H265 after every VP9 download.

play:
Just replace the 2 webm with mp4
https://github.com/kochd/electricsheep-hd-client/blob/master/play#L16

**Comment by kochd** [comment]
Intel Celeron J3160 SoC supports VP9 decoding and is relatively cheap

**Comment by earsneyes** [comment]
Thanks for the directions, i had this in mind as well. Will try it and look at hardware with J3160 Celeron.
