### ISSUE TITLE
Please confirm GPU render stability

### ISSUE THREAD

**Issue by StanekO** [kochd/electricsheep-hd-client#37]
Hi, I found 3 sheeps:

- electricsheep.244.00339.11785_electricsheep.244.00340.11290.webm
- electricsheep.244.00339.11785_electricsheep.244.00339.11785.webm
- electricsheep.244.00338.05993_electricsheep.244.00339.11785.webm
- electricsheep.244.00274.10152_electricsheep.244.00274.10152.webm

Both are blinking and have some wrong "validated by", should we check render stability on diferent HW, or it is the way, how are these sheeps designed = "blinking"?

**Comment by kochd** [comment]
Could be something like this:
https://github.com/kochd/electricsheep-hd-client/issues/13#issuecomment-391510705

This is probably due to OpenCL implementations by the GPU vendors. This will probably never be fixed and is way out of my possibilities. Different environments render the frames differently sometimes. 
Usually this means that someone is producing slightly different results than anybody else. 
Never saw this with cpu rendering.

@earsneyes looks like the frames are yours. 
I'll have to check the sequences later.

**Comment by earsneyes** [comment]
let me know if you find something. i noticed these sheeps as well but thought they are the ones we need to compute/render again.

**Comment by StanekO** [comment]
Can we increase number of validations? For better diagnostic? Are all users GPU using the same rendering process/solver?

**Comment by kochd** [comment]
electricsheep.244.00339.11785_electricsheep.244.00340.11290
365 by lp
![00365](https://user-images.githubusercontent.com/1825660/65728913-b9f7a980-e0bc-11e9-9425-2018bce58678.jpg)
366 by lp
![00366](https://user-images.githubusercontent.com/1825660/65728928-c8de5c00-e0bc-11e9-8a68-04068fe2a6ea.jpg)
370 by
![00370](https://user-images.githubusercontent.com/1825660/65728972-edd2cf00-e0bc-11e9-9794-a0a30e3e32be.jpg)
371 by lp
![00371](https://user-images.githubusercontent.com/1825660/65728978-f4f9dd00-e0bc-11e9-8cfc-0c7c6a78df16.jpg)



360-365 is one batch of work. so i thing one machine of @earsneyes is misbehaving
366-370 are bad

**Comment by highdefractal** [comment]
@StanekO is your GPU running really hot or overclocked? just a guess that could cause bad images

**Comment by earsneyes** [comment]
@highdefractal  nope both GPU's are running cool and stock speeds.
Thinking about this i ask myself what driver (nvidia) and fractorium versions others are running ?

I try to isolate the problem to get the misbehaving machine figured out.

**Comment by kochd** [comment]
The GPU results are not that reproduce able. Also it does not happen for all frames.

**Comment by StanekO** [comment]
Have you thought about about increase number of validations? I think, more sheeps can be affected..

**Comment by kochd** [comment]
The problem is that in the GPU branch there is no definitive correct way to render a frame as some OpenCL implementation seam to be different. The worker who sends in frames that are invalid for you will of course also treat your frames as invalid but which one is the _correct_ one?
Everyone would have to render every frame to determine whats the most common way to render it. And even if we would do that if more people would use _(Hardware,OS,Driver Version)_ that consensus would shift in the middle of a sequence. I don't think that problem would be solved that way. The implementations are screwed and that is the actual problem here.

**Comment by kochd** [comment]
http://fractorium.com/?article=amd-vs-nvidia

**Comment by earsneyes** [comment]
Maybe looking at what hardware / software / driver versions people using can help ?
At home I'm on a nvidia 1050 Ti, driver is 416.34 on Win 10 64. Fractorium version is 1.0.0.17.

**Comment by kochd** [comment]
Test case:

https://sheeps.triple6.org/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.00339.11785_electricsheep.244.00340.11290.flame.gz

unzip

render 365-371
<pre>
emberanimate --in=electricsheep.244.00339.11785_electricsheep.244.00340.11290 --format=jpg --opencl --sp --supersample=2 --begin 364 --end 371 --isaac_seed=fractorium
</pre>

**Comment by kochd** [comment]
![0365](https://user-images.githubusercontent.com/1825660/65899205-85813780-e3b3-11e9-815c-034cc23297ff.jpg)
![0366](https://user-images.githubusercontent.com/1825660/65899204-84e8a100-e3b3-11e9-8f6f-846d191c4f7f.jpg)
![0367](https://user-images.githubusercontent.com/1825660/65899203-84e8a100-e3b3-11e9-9dc4-43425e7f5c20.jpg)
![0368](https://user-images.githubusercontent.com/1825660/65899202-84e8a100-e3b3-11e9-959a-cd0c519d589f.jpg)
![0369](https://user-images.githubusercontent.com/1825660/65899226-903bcc80-e3b3-11e9-9b2f-30bbf13f52ed.jpg)
![0370](https://user-images.githubusercontent.com/1825660/65899227-903bcc80-e3b3-11e9-9f10-3b7a5b82887e.jpg)
![0371](https://user-images.githubusercontent.com/1825660/65899228-903bcc80-e3b3-11e9-9b4f-98e944f8e4a3.jpg)

AMD Rocm GNU/Linux

**Comment by StanekO** [comment]
OK, i understand...

`C:\Users\StanekO\AppData\Roaming\Fractorium>emberanimate --in=electricsheep.244.00339.11785_electricsheep.244.00340.11290.flame --format=jpg --opencl --sp --supersample=2 --begin 364 --end 371 --isaac_seed=fractorium`

![IntelHD630-GTX1050Ti](https://user-images.githubusercontent.com/29358013/65903538-df3a2f80-e3bc-11e9-970e-0370e2a01297.jpg)
IntelHD630-GTX1050Ti

![GTX980M](https://user-images.githubusercontent.com/29358013/65904217-4dcbbd00-e3be-11e9-97ed-b101b71b9206.jpg)
GTX980M

In the end, we must to find some solution. I have found like 10-20 buggy sheeps like this: `D:\Programy\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KY38402AGPU\movies\electricsheep.244.00385.12805_electricsheep.244.00385.12805.webm`
I have check all frames 0-360.jpg (render time=1h2m) and there are no jumps in camera like in this.webm

![0180](https://user-images.githubusercontent.com/29358013/65904958-e7e03500-e3bf-11e9-8950-6de7203ec4f1.jpg)
electricsheep.244.00385.12805_electricsheep.244.00385.12805_0180.jpg

I dont know, if it is bug of fractorium, or if it will be possible to mix results from AMD & Nvidia to 1 video any more... Results are not good..
Should server to send you a testing task to decide, if you are compatible AMD/Nvidia and report this to running daemon.session?  Or better, first to check compatibility on each sheep 50-55&300-305.jpg?

**Comment by kochd** [comment]
@StanekO could you try that again without the <code>--sp</code> parameter? I would like to know if that makes any difference.
What could we do with clients that behave differently? People are not able to fix this. And who is even right? Is my result or your result the correct one?
``I have check all frames 0-360.jpg (render time=1h2m) and there are no jumps in camera like in this.webm ``
If i would do that it would be same for me: No jumps - but it would look completely different than your result. The jumps happen because we obtain X frames from A and Y frames B which get connected but do not fit together.
NVIDIA does it wrong so we would have to ban all NVIDIA users. Fractorium already mentioned this and its a known problem with NVIDIA and OpenCL.

http://fractorium.com/?article=amd-vs-nvidia

**Comment by StanekO** [comment]
![no--sp](https://user-images.githubusercontent.com/29358013/65914900-91c8bd00-e3d2-11e9-9635-77f4301e4759.jpg)
There is no significant change, by parametr `no --sp` but i takes 10min more = 1m vs 11m

What about:
```
userA [716.A][717.A][718.A][719.A][720.A]
userB ............................[720.B][0.B][1.B][2.B][3.B][4.B][5.B]
userC ............................................................[5.C][6.C][7.C][8.C][9.C][10.C]
```
and check if [5.B] != 99% [5.C] then delay? It will disable NVIDIA at problematic sheeps..

**Comment by kochd** [comment]
That is already implemented. If a submitted frame has too much difference to the frame before it will not be accepted. The threshold has too be kinda high because some sheeps move really fast and therefore change much from frame to frame.
As everything is a linear transaction that would effectively exclude NVidia from rendering frames that have xforms they cant handle.
Also keep in mind that there is no clear cut at frame 720A. 0B will have to be close to 720A. And that is the case for every frame. Even if every client has to render 360 frames at once there will be flickering. It will be less of course but it also opens up for denial of service attacks.

**Comment by kochd** [comment]
I am thinking of hardware test based on these issues which move clients into a GPU:NVIDIA branch.

**Comment by StanekO** [comment]
I don't understand. Can you please check `electricsheep.244.00339.11785_electricsheep.244.00340.11290.flame` in Fractorium.exe? I am geting the same picture by using CPU..
![Poznámka 2019-10-01 113013](https://user-images.githubusercontent.com/29358013/65951328-274e6600-e440-11e9-9b5e-d6e41b79a471.jpg)

**Comment by kochd** [comment]
Well looks like fractorium is broken now as-well. Somewhere between 1.0.0.8 and 1.0.0.17.
Here is what flam3 (as the definitively correct implementation) produces as result (frame 365):
![foo00365](https://user-images.githubusercontent.com/1825660/65980300-28e75080-e477-11e9-966a-0cc2613cd40f.jpg)

With fractorium 1.0.0.17 I am get the same result as you do.
https://bitbucket.org/mfeemster/fractorium/src/4a150132e1a1c801ffa6e18264abe8d680c9c0bc/Data/Version%20History.txt#lines-293
looks really suspicious to me and might be the cause for this.

**Comment by kochd** [comment]
https://bitbucket.org/mfeemster/fractorium/issues/27/flam3-compatibility-after-1008

**Comment by kochd** [comment]
@earsneyes you should be using two different versions then. correct?

**Comment by earsneyes** [comment]
i updated fractorium on both machines last week. so i think they are both running 1.0.0.17.

**Comment by StanekO** [comment]
> Also keep in mind that there is no clear cut at frame 720A. 0B will have to be close to 720A. And that is the case for every frame. Even if every client has to render 360 frames at once there will be flickering. It will be less of course but it also opens up for denial of service attacks.

I was thinking not about compare 720.A to 0.B, but 720.A to 720.B to check results/compatibility AvsB at the same frame to accept 0.B
But, in the end I'm really glad/happy, that we have found a potential problem/issue at Fractorium side..

**Comment by highdefractal** [comment]
i couldn't find a download link but i had 1.0.0.16 for Windows which i uploaded here. i got it from the official fractorium.com site in June and have it installed on my local machine. i didn't realize i could attach files on github until typing this message so the same file is also here. had to zip for github, it wouldn't let me attach the .msi 

https://gofile.io/?c=GKT4p2

[Fractorium_1.0.0.16.zip](https://github.com/kochd/electricsheep-hd-client/files/3679309/Fractorium_1.0.0.16.zip)

**Comment by highdefractal** [comment]
i'm running fractorium 1.0.0.17 on another machine i use for this project. i can grab the geforce driver number if it helps but it's fairly new, pulled from nvidia.com maybe 2 weeks ago

**Comment by kochd** [comment]
https://bitbucket.org/mfeemster/fractorium/issues/27/flam3-compatibility-after-1008#comment-54162100

> I changed cot and a few other variations (see the commit log) to match what Chaotica does. More people use and care about Chaotica, than old flam3, so I opted for compatibility with the former.

- This is **bad news** for our project.
- Chaotica in the free (as in money) version is not suitable for what we do

**Comment by kochd** [comment]
Thank you @highdefractal. We know now that this issue was introduced with fractorium 1.0.0.16.

**Comment by highdefractal** [comment]
using the above test case from @kochd with nvidia 436.02 and fractorium 1.0.0.16 i get the "BAD" dark images though. i can borrow an AMD machine tomorrow for testing

**Comment by highdefractal** [comment]
could we just keep using fractorium version <= 1.0.0.15 for the project?

**Comment by earsneyes** [comment]
a compatibility mode would be good. 
will downgrading the fractorium to 1.0.0.15 or older solve the issue for now ?
I want the glitch free line of sheeps back.

**Comment by kochd** [comment]
Two options:

1. Everyone uses 1.0.0.15 or before
2. Everyone uses 1.0.0.16 or later

Option 1 is the preferred one as the result should look more aesthetic in almost every case. However i wasn't able to find any old builds for now. As fractorium is open source and available in a versioning system i will be able to cross compile the 1.0.0.15 release myself.

**The current plan is to go for Option 2 for now.**   

1. I'll have to implement a lock on server side to prevent people from submitting with an unwanted version.  
2. Get the binaries for the 1.0.0.15 release
3. Force everyone to downgrade by using the lock from 1.

Still hoping for fractorium to commit in providing flam3 compatibility in the future

**Comment by StanekO** [comment]
OK, I will contunue on: **1.0.0.17** and wait for next step...

I found 1.0.0.14: [https://web.archive.org/web/*/http://fractorium.com/](url) 

- Windows: [https://drive.google.com/open?id=1qBkG4_h8lyOFTeegY_ft34UCMYelqiHV](url)
- Ubunutu: [https://launchpad.net/~fractorium/+archive/ubuntu/ppa/+files/fractorium_1.0.0.14-0ubuntu1_amd64.deb](url)

**Comment by kochd** [comment]
Matt Feemster will put a compatibility option into fractorium :tada:

**Comment by kochd** [comment]
I will still have to maintain our own builds that utilize this option. Its probably not the worst idea to maintain our own fractorium build so we know what version is actually used. This will take some work to set up the build environments for this.
