### ISSUE TITLE
Windows 10 Debian Linux subsystem, Error: execution expired

### ISSUE THREAD

**Issue by arman68** [kochd/electricsheep-hd-client#4]
No matter what I tried with the path and location of the files, I could not get the daemon-windows.cmd to work, SO I have installed the Debian Linux subsystem. Managed to get everything installed easily, and launched the daemon, but it does not seem to be rendering anything. Here is what I get:

```
./daemon --apikey <...>
./daemon:20: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
From https://github.com/kochd/electricsheep-hd-client
 * branch            master     -> FETCH_HEAD
./daemon:20: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Active season: G244_W1920_H1080_Q5000_KLq5pt28
Requesting new sequence ...
Not enough credits. Render 10 more frames.
Requesting new work...
Error: execution expired
Active season: G244_W1920_H1080_Q5000_KLq5pt28
Requesting new sequence ...
Not enough credits. Render 10 more frames.
Requesting new work...
Error: execution expired
Error: execution expired
Error: execution expired
Active season: G244_W1920_H1080_Q5000_KLq5pt28
Requesting new sequence ...

**Comment by kochd** [comment]
Hello.

I'll have a look into this.
For the record: Is this output from your WSL or your native installation?

**Comment by kochd** [comment]
![2018-05-07-230802_1576x849_scrot](https://user-images.githubusercontent.com/1825660/39725364-c1d854a2-524b-11e8-8621-e4f26dfa2609.png)

Here is what happens on Windows 7 when you do it correctly

**Comment by kochd** [comment]
Looks like your output is from WSL. Currently you are rendering. Was there something you did to fix the `Error: execution expired` error?

**Comment by GeorgeHahn** [comment]
I observe a couple of errors when running on Windows 10.

1. The `git_flam3_ruby.zip` does not include `which`, causing `daemon` to crash at line 20.
2. After commenting out lines 20-21, the output is as follows:

```
C:\Users\user\Downloads\electricsheep-hd-client-master>ruby daemon    || pause
fatal: Not a git repository (or any of the parent directories): .git
C:/Users/user/Downloads/electricsheep-hd-client-master/git+flam3+ruby/lib/ruby/2.1.0/uri/generic.rb:1203:in `rescue in merge': bad URI(is not URI?): api/active_season?apikey=ÿ_<key, printed with spaces after each character>(URI::InvalidURIError)
        from C:/Users/user/Downloads/electricsheep-hd-client-master/git+flam3+ruby/lib/ruby/2.1.0/uri/generic.rb:1200:in `merge'
        from daemon:50:in `get'
        from daemon:152:in `block in <main>'
        from daemon:149:in `loop'
        from daemon:149:in `<main>'
```

After converting api.key from UCS2-xE BOM (I think it was -LE) to UTF-8, the daemon starts and is able to begin rendering.

**Comment by kochd** [comment]
I am planing to develop a build system which is able to produce an installer containing everything needed. Also Linux just got a way for playing the results and a working screensaver. Windows still lacks these two key features.

@GeorgeHahn if i understand you correctly there are currently two problems:

1. The environment is missing `which`
2. We need to force UTF-8 encoding when reading the `api.key` file 

Can you confirm this?

**Comment by GeorgeHahn** [comment]
1. Correct
2. No - this appears to be the default behavior. The `echo` command displayed by the website will cause the api.key file to be written with non-UTF8 encoding. I'm not aware of an elegant way to solve this. One way would be to have the user pass the api key to the daemon and let the daemon persist the key.

**Comment by arman68** [comment]
In WSL, you are right, it eventually work, but I keep getting frequent "Error: execution expired". I think this might be due to my internet connection: I just installed a new TV a couple of days ago, and it might be acting as a faraday cage, blocking some of the WiFi signal. I am investigating.

For the Windows 10 version, I just managed to get it working, thanks to the hints provided:
* I added the api key as a parameter in the .cmd file (--apikey <...>)
* In daemon script, I commented out the lines 20 and 21 (calling which)
* In daemon script, I commented out line 60 (calling git)
I think the syntax for calling the tools with the backquote might be the problem.

It is currently running fine, natively in Windows 10, with the above changes:
```
C:\TOOLS\electricsheep-hd\client>cd \TOOLS\electricsheep-hd\client\

C:\TOOLS\electricsheep-hd\client>set PATH=(...);;C:\TOOLS\electricsheep-hd\client\git+flam3+ruby\bin

C:\TOOLS\electricsheep-hd\client>ruby daemon --apikey (...)   || pause
Active season: development
Requesting new sequence ...
Not enough credits. Render 7 more frames.
Requesting new work...
Downloading electricsheep.244.00001.01696_electricsheep.244.00001.01696 ...
Rendering... electricsheep.244.00001.01696_electricsheep.244.00001.01696 Frame 9
chaos:  36.1%  ETA: 11.7 minutes

**Comment by arman68** [comment]
I also suggest changing line 115 in daemon, to run the flam3-animate process at idle priority:
```
    `start /low /b flam3-animate`

**Comment by kochd** [comment]
The execution of `git` and `which` is skipped for now

**Comment by kochd** [comment]
I am closing this issue as @arman68 has a working client now.
