### ISSUE TITLE
GPU Rendering Hangs

### ISSUE THREAD

**Issue by ElectricShperson** [kochd/electricsheep-hd-client#40]
I'm having trouble getting my GPU to render consistently. When I first installed everything and started the GPU daemon it would solve the PoW and then hang on: 
"Stage = iterating, progress = 100%, eta = 0.00s"
While it does this my GPU is running at 100% but appears to be making no progress. I tried leaving it this way for an hour to see if it would do anything differently but it just sat there until I closed the daemon.

After I fired up the CPU daemon and that worked just fine, I went back to test the GPU and it worked for nearly an hour before doing the same thing again. Below is a screenshot of the daemon after it ran successfully for a while and then got stuck again:

![ElectricSheepDaemon](https://user-images.githubusercontent.com/57150265/67798419-71cbfe00-fa51-11e9-89fe-267666cf727b.png)

CPU is an Intel 7920X
GPU is an Nvidia 2080 Ti

**Comment by kochd** [comment]
You could try to update your drivers. Nvidia istn't the best when it comes to OpenCL.
