### ISSUE TITLE
bad URI?

### ISSUE THREAD

**Issue by earsneyes** [kochd/electricsheep-hd-client#45]
Since the last update my client on one of my servers does not work.
It spits the following error:

`[09:23:44] INFO: Active season: G244_W1920_H1080_Q1024_K1C1DF3M
[09:23:44] INFO: Cleaning up animated genomes...
[09:23:44] INFO: Hashing files for p2p announce
/usr/share/ruby/uri/generic.rb:1203:in `rescue in merge': bad URI(is not URI?): api/p2p/announce?apikey=P6uXgDqHy_QdQixEbCZ4abUbnb9d1N_2WKu3PGegitKxEAN4FLWgVSGfbA&gpu=false&files=[{"name":"electricsheep.244.00440.02518_electricsheep.244.00441.03001.webm","hash":"0e4739930419547d99eb09178b811afd5bda1e5de88e6fa131be8468cf1cc5d1"},{"name":"electricsheep.244.00440.02518_electricsheep.244.00440.02518.webm","hash":"e620bc694f84ad718327626913a52156ac8467e290b96b13099255fefa84895f"},{"name":"electricsheep.244.00441.03001_electricsheep.244.00442.01656.webm","hash":"cbcf999f79f8f86d44a1ee1c4ad02fc91a35893c7e2c35a183e548b57d431953"},{"name":"electricsheep.244.00439.02674_electricsheep.244.00439.02674.webm","hash":"d046a48ba269cdb69b7d32c68086deebeee7e244903cd6c586fd8c5aa19c2e34"},{"name":"electricsheep.244.00441.03001_electricsheep.244.00441.03001.webm","hash":"7685207e03adf08940806d110d5c88e2cea18c0d550067b02cbd826e3be753a1"}] (URI::InvalidURIError)
        from /usr/share/ruby/uri/generic.rb:1200:in `merge'
        from /home/linus/electricsheep-hd-client/daemon:126:in `get'
        from /home/linus/electricsheep-hd-client/lib/p2p.rb:21:in `block in announce'
        from /home/linus/electricsheep-hd-client/lib/p2p.rb:20:in `each'
        from /home/linus/electricsheep-hd-client/lib/p2p.rb:20:in `announce'
        from /home/linus/electricsheep-hd-client/daemon:383:in `block (2 levels) in <main>'
        from /usr/share/ruby/timeout.rb:66:in `timeout'
        from /home/linus/electricsheep-hd-client/daemon:383:in `block in <main>'
        from /home/linus/electricsheep-hd-client/daemon:353:in `loop'
        from /home/linus/electricsheep-hd-client/daemon:353:in `<main>'`

On my older machine it worked right away.
Any idea ?

**Comment by kochd** [comment]
Couldn't reproduce. i reverted all these changes. Needs more investigation.

**Comment by kochd** [comment]
Looks like a formatting issue ... kind off...

```ruby
[10] pry(main)> files = [{"name":"electricsheep.244.00440.02518_electricsheep.244.00441.03001.webm","hash":"0e4739930419547d99eb09178b811afd5bda1e5de88e6fa131be8468cf1cc5d1"},{"name":"electricsheep.244.00440.02518_electricsheep.244.00440.02518.webm","hash":"e620bc694f84ad718327626913a52156ac8467e290b96b13099255fefa84895f"},{"name":"electricsheep.244.00441.03001_electricsheep.244.00442.01656.webm","hash":"cbcf999f79f8f86d44a1ee1c4ad02fc91a35893c7e2c35a183e548b57d431953"},{"name":"electricsheep.244.00439.02674_electricsheep.244.00439.02674.webm","hash":"d046a48ba269cdb69b7d32c68086deebeee7e244903cd6c586fd8c5aa19c2e34"},{"name":"electricsheep.244.00441.03001_electricsheep.244.00441.03001.webm","hash":"7685207e03adf08940806d110d5c88e2cea18c0d550067b02cbd826e3be753a1"}]
=> [{:name=>"electricsheep.244.00440.02518_electricsheep.244.00441.03001.webm",
  :hash=>"0e4739930419547d99eb09178b811afd5bda1e5de88e6fa131be8468cf1cc5d1"},
 {:name=>"electricsheep.244.00440.02518_electricsheep.244.00440.02518.webm",
  :hash=>"e620bc694f84ad718327626913a52156ac8467e290b96b13099255fefa84895f"},
 {:name=>"electricsheep.244.00441.03001_electricsheep.244.00442.01656.webm",
  :hash=>"cbcf999f79f8f86d44a1ee1c4ad02fc91a35893c7e2c35a183e548b57d431953"},
 {:name=>"electricsheep.244.00439.02674_electricsheep.244.00439.02674.webm",
  :hash=>"d046a48ba269cdb69b7d32c68086deebeee7e244903cd6c586fd8c5aa19c2e34"},
 {:name=>"electricsheep.244.00441.03001_electricsheep.244.00441.03001.webm",
  :hash=>"7685207e03adf08940806d110d5c88e2cea18c0d550067b02cbd826e3be753a1"}]
[11] pry(main)> Net::HTTP::Get.new("http://sheeps.triple6.org/api/p2p/announce?apikey=P6uXgDqHy_QdQixEbCZ4abUbnb9d1N_2WKu3PGegitKxEAN4FLWgVSGfbA&gpu=false&files")
=> #<Net::HTTP::Get GET>

[12] pry(main)> Net::HTTP::Get.new("http://sheeps.triple6.org/api/p2p/announce?apikey=P6uXgDqHy_QdQixEbCZ4abUbnb9d1N_2WKu3PGegitKxEAN4FLWgVSGfbA&gpu=false&files=#{work.to_json}")
=> #<Net::HTTP::Get GET>
```

**Comment by kochd** [comment]
![2019-12-17-1576611006](https://user-images.githubusercontent.com/1825660/71027722-1989b200-210c-11ea-8b1e-0eeddd67dd96.png)

Even works on windows for me.
Can you provide more info? Which OS? 

if Windows:
Anything special like a local installation of ruby which could be overwriting the embedded version?
Just open a cmd and run <pre>ruby --version</pre>

**Comment by kochd** [comment]
Looks like you are using Linux with a local ruby /usr/share/ruby/uri/generic.rb

I am using 
<pre>ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]</pre>

The windows build uses
<pre> ruby 2.6.4p104 (2019-08-28 revision 67798) [x64-mingw32] </pre>

i am guessing you are using an older version that?

**Comment by kochd** [comment]
This could fix your problem with older ruby versions:

``` diff
--- a/daemon
+++ b/daemon
@@ -123,7 +123,7 @@ class API
   end
 
   def get(url, &block)
-    uri = @uri + url
+    uri = @uri + URI.escape(url)
```

**Comment by earsneyes** [comment]
Indeed it was the older ruby version on a centOS Server. works now :) Thanks!

**Comment by kochd** [comment]
Did you apply the suggested patch or did you just update your ruby?

**Comment by earsneyes** [comment]
I just applied the patch because of lazyness :)
