### ISSUE TITLE
Are the Vp9 Jobs broken on the server?

### ISSUE THREAD

**Issue by hdusten** [kochd/electricsheep-hd-client#47]
I wasn't sure where to pit this but as of writing this there are 88 pending jobs on the server. Yesterday there was an issue with the daemon where it was expecting an output file from emberanimate without the preceding 0. I modified my daemon file to correctly parse I believe it was 2 flames before going back to normal. I wonder if the jobs on the server are affected by those 2 flames.

Thought I would say something is all. Thanks.

**Comment by kochd** [comment]
Hello.

No its actually processing the input but at lower rate than the input. I am currently waiting for the arrival of a new processor (Ryzen 2700x) which should solve that issue.
The first item in the of rendering jobs should be the one which is currently being rendered.

**Comment by hdusten** [comment]
Got it, thanks for the response!

That's partly my bad - I've been running at about 10k frames a day on my end. I'm Aquaritek ;). Hoping to continue my contribution for some time. I became interested in the Electric Sheep vision years and years ago and I'm glad to have stumbled across someone who finally wanted to parse sheep in high resolution.

Thank you!

**Comment by kochd** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L9 looks like ffmpeg 4.3 will enable me to use my GPU for this...

**Comment by hdusten** [comment]
Is the server out of space or did the cleanup job lock up?

**Comment by kochd** [comment]
The server will automatically clean up things not needed anymore with a hourly running job. There are phases where we run out of disk space and cant accept any submissions. Once some time is passed the server starts to accept submissions again.

**Comment by kochd** [comment]
Currently its accepting again
