### ISSUE TITLE
PoW Difficulty

### ISSUE THREAD

**Issue by hdusten** [kochd/electricsheep-hd-client#49]
Good Day,

I've been watching my clients operational patterns and have noticed that on average - time to solve PoW takes a fairly long time. EDIT: having actually coded some statistics into the daemon please see the screenshot below for an actual account.

Wondering if PoW needs to be that difficult in a scenario like this? I feel like that definitely slows down time to render and hurts the FPM averages. I thought about this and it could be designed that way - as a throttle of sorts.

If this was a more critical application I could understand difficult PoW resolutions. I'm wondering what the idea was. I would almost think a PoW should be requested and granted a success state for some random amount of time so that it doesn't have to keep solving for it at every single step of the process.

These are just thoughts. Have a great day.

EDIT: I wrote a fairly basic statistics class into the daemon if you wanted to take a look. I'll take a screenshot after one of my clients runs for a significant amount of time all of the stats are in memory at this time. May write it out to Json file at some point so it averages out over long periods of time in the future.

However, I'm not familiar with Ruby just picked up the basics by reading through the daemon

EDIT:
After one of the clients ran without issue through the night - I'll replace the screenshots I had before with this one that has a more balanced figure over time for the stats.

![image](https://user-images.githubusercontent.com/5505322/72540362-f0a92980-383d-11ea-9e78-745bcb9985a2.png)

This gives a much clearer picture of what the machine's time is dedicated to and particularly that nearly a quarter of the time is spent solving for PoW.

**Comment by kochd** [comment]
Hi hdusten,

Thank you for reporting this.

We had the concept of giving the ones with a high trust level an easier pow than the others. Looks like i reversed that at some point in time but i really cant remember why at the moment just that it was situational. I've now re-enabled it and the pow should now be solved within <5s for you. 

The pow scales really bad as its either too easy or too hard. The implementation in the daemon itself is not concurrent. I had the plan of offloading it to a compiled binary which solves the pow concurrently so it uses the total amount of computing power.

The whole purpose of the PoW is actually to delay your requests against operations that trigger, or potentially trigger high load on server. This prevents brute force, denial of service, makes it time consuming to reverse engineer the protocol, and so on. 
But the trust score system already prevents from a lot of these things so PoW is just on top of that to add an additional layer. 

Reference: https://github.com/kochd/electricsheep-hd-client/issues/16

As of your statistics generator it look pretty useful if you need runtime measurements  but i think its nothing useful to the bread and butter user.
But FYI as you dig around with ruby: https://ruby-prof.github.io/ there is a really generic approach that lets you profile any code and tells you where you spend your time. The implementation in the daemon is as easy as:
``` ruby
require 'ruby-prof'
RubyProf.start
# Patch the existing trap
SIGNAL.trap("int"){
result = RubyProf.stop
printer = RubyProf::FlatPrinter.new(result)
printer.print(STDOUT)
exit
}
#(untested) 
```
of course this will give you a ton of information and is far more unspecific than your approach.

**Comment by kochd** [comment]
https://rbspy.github.io/ there's also rbspy which lets you hook into any running process without even have to change the code.
