### ISSUE TITLE
Evaluate possibility of rendering on GPU

### ISSUE THREAD

**Issue by GeorgeHahn** [kochd/electricsheep-hd-client#5]
[fractorium](https://bitbucket.org/mfeemster/fractorium) ([homepage](http://fractorium.com/))

- Much faster rendering
- Actively maintained
- Renders differently than flam3

-----
<s>
From [cuburn](https://github.com/stevenrobertson/cuburn):

> This project is a fractal flame renderer, similar to flam3, built for CUDA GPUs. It also includes a new blending system, the ability to perform spline-based animation of individual parameters over time, and new, HDR-aware filtering mechanisms. The overall result is a distinctive, dreamlike atmosphere — rendered up to one hundred times faster than CPU.

Improvements:

- Much faster rendering
- (Theoretically) nicer rendering

Challenges:

1. cuburn does not render images exactly the same as flam3
2. cuburn depends on the Cuda toolkit, which is 1+ GB
3. cuburn has some Python dependencies

I suspect the second and third issues are reasonably surmountable. What do you think about the first?
</s>

**Comment by kochd** [comment]
Hello George,
The first one wouldn't be a problem if the whole sequence or even a whole parallel season would be rendered isolated from the CPU renders.

I had another issue with cuburn 3 years ago (https://github.com/stevenrobertson/cuburn/issues/3) and never got an answer. But ill have a look into it again.

We use sequences to animate a genome either into itself or into another genome ( just the way electric sheep does it ).

Currently i am not sure what exactly was the problem with cuburn.
If you want to try it with cuburn you can use the files in `branches/G244_W1920_H1080_Q5000_KLq5pt28/animated_genomes/`

**Comment by GeorgeHahn** [comment]
After some investigation, cuburn appears to be broken in multiple places. Tested with Cuda toolkit 9.1 on Windows 10.

**Comment by GeorgeHahn** [comment]
[Fractorium](http://fractorium.com/) works quite nicely!

Comparison between flam3 and Fractorium renders:

flam3:
![frame_18_flam3_electricsheep 244 00003 01376_electricsheep 244 00003 01376](https://user-images.githubusercontent.com/502747/39741312-fc3879c8-5288-11e8-9901-bc92b837a84f.jpg)

Fractorium:
![frame_18_fractorium_electricsheep 244 00003 01376_electricsheep 244 00003 01376](https://user-images.githubusercontent.com/502747/39741320-0353d612-5289-11e8-9b1b-340924072eff.jpg)

Total time to render (on my crappy GTX760): 12.42 seconds @ double precision

**Comment by kochd** [comment]
We now have the `--experimental-gpu` switch which makes use of [fractorium](http://fractorium.com/).
Thanks to @GeorgeHahn for implementing this.
