### ISSUE TITLE
Open-source the server code

### ISSUE THREAD

**Issue by Epholys** [kochd/electricsheep-hd-client#51]
Hello,

This is an awesome project, I really loved the original electricsheep and having a hd version is really cool!

I would like to ask if you have any plan to put the source code from the server on GitHub? I think it's important to have some kind of public backup of the code, in case of hardware failure for example.
It doesn't have to be a really pretty and ready-to-use clean repo, but it would be great.

**Comment by kochd** [comment]
Hello @Epholys,

Currently there are no plans to publicly release the code. If however I ever abandon this project it will be released.
