### ISSUE TITLE
Frames out of order on some renders in new GPU season

### ISSUE THREAD

**Issue by highdefractal** [kochd/electricsheep-hd-client#52]
@kochd Hey I've noticed that some of the renders look like they jump or twitch on the new GPU season G244_W3840_H2160_Q1024_KFVGM5cUGPU. Initially I thought this may be something with my local machine I was using to view the videos or possibly just something different with the new season but may have tracked down the cause.

I just updated fractorium and I believe this could be related to using a fractorium builds > 1.0.0.18. It looks like if build 1.0.0.19 or 1.0.0.20 is used it offsets the frame numbering and to be out of order. Frames 600-605 becomes 598-603 or something like that. I can reproduce on my machine but it runs the risk of uploading bad frames to the project in doing so. I have not tried using the --flam3_compat option with these builds installed as I was not 100% sure of all the changes needed in the daemon to fix. One example is electricsheep.244.00278.03932_electricsheep.244.00279.11673.webm at the 3 second mark. It seems to jump elsewhere in this render but that one seems much more noticeable. I rolled back to 1.0.016 which appears to work correctly.

P.S. Thank you for your time and effort in running this project! The fractals keep getting better and better! If I can assist in troubleshooting this let me know.

**Comment by kochd** [comment]
It kinda shifts the center: 
![mpv-shot0014](https://user-images.githubusercontent.com/1825660/80315691-8f5c0380-87f9-11ea-9887-a0e86b1d866d.jpg)

![mpv-shot0015](https://user-images.githubusercontent.com/1825660/80315687-89feb900-87f9-11ea-8e1f-d5b558de7c33.jpg)

My first guessing is that the frames with this offset where rendered by someone else. I am currently investigating this...

**Comment by kochd** [comment]
Looks like ✯ electricsheep is submitting these frames and lost almost all his trust due to that. However he stopped rendering. I dont think i can contact him on that because he used a faked mail address. However if he will continue with this even without knowing a ban will automatically kick in.

As his trust is so low all the frames that where validated by someone else got replaced with correct ones. Sadly we can not double check every frame :(. However I am glad that the system I designed actually is able to solve those problems on its own.

**Comment by kochd** [comment]
I am closing this for now. If you find another example that is related to another user feel free to reopen it. We need someone with a proper mail address to be able to get behind whats actually wrong here.

I was able to investigate this by checking based on the mentioned sequence id: _electricsheep.244.00278.03932_electricsheep.244.00279.11673_ who rendered which frame by looking at:

https://sheeps.triple6.org/frame/G244_W3840_H2160_Q1024_KFVGM5cUGPU/electricsheep.244.00278.03932_electricsheep.244.00279.11673

This works with any frame id

**Comment by kochd** [comment]
Another example of the difference for the record:

![mpv-shot0017](https://user-images.githubusercontent.com/1825660/80316380-c207fb00-87fd-11ea-931b-c5cc9458aca3.jpg)
![mpv-shot0016](https://user-images.githubusercontent.com/1825660/80316382-c46a5500-87fd-11ea-8f4a-2912f8945dfb.jpg)

**Comment by highdefractal** [comment]
I agree that the checking system you put in place works very well. There is a few other renters that suffer from this issue and I can go through them if you're interested in rerendering but it's your call. I am fine with rerendering or leaving them as is. Again, thank you for all your work on this project!
