### ISSUE TITLE
GPU daemon: Frames rendered in a given set are off-by-one

### ISSUE THREAD

**Issue by lordastley** [kochd/electricsheep-hd-client#54]
The frames rendered are off-by-one from the frames stated as being rendered.
For the example below, Frame 331-335 are stated as being rendered. However, the files output are numbered 330-334.jpg, and appear to correspond to frames 330-334.

Computer Info:
Windows 10 x64 1909
electricsheep-hd-client 20190923
fractorium 1.0.020
Nvidia GeForce GTX 1060, 6 GB, driver 26.21.14.4614

```
C:\Program Files (x86)\Electric Sheep HD>ruby daemon --gpu   || pause
[elided]
[22:20:10] INFO: Active season: G244_W3840_H2160_Q1024_KFVGM5cUGPU
[22:20:10] INFO: Cleaning up animated genomes...
[22:20:10] INFO: Requesting new work...
[22:20:10] INFO: Solving PoW...
[22:20:13] INFO: Solved after 3 seconds
[22:20:19] INFO: Rendering... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 331-335
Using OpenCL to render.
Parsing ember file C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KFVGM5cUGPU/animated_genomes/electricsheep.244.00520.04286_electricsheep.244.00520.04286.flame
Finished parsing.
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Finished in: 1m 6.35s
[22:21:26] INFO: Uploading... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 331
[22:21:46] INFO: Uploading... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 332
[22:22:04] INFO: Uploading... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 333
[22:22:23] INFO: Uploading... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 334
[22:22:42] INFO: Uploading... electricsheep.244.00520.04286_electricsheep.244.00520.04286 Frame 335
[22:22:42] ERROR: No such file or directory @ rb_sysopen - C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KFVGM5cUGPU/frames/electricsheep.244.00520.04286_electricsheep.244.00520.04286/0335.jpg
```

**Comment by kochd** [comment]
This is due to the fact that fractorium counts from zero while flam3 counts from 1. Therefore the offset.

e.g:
If the server request frame 1 from a fractorium client it will have to render 00000.jpg which is treated as frame 1 on server side as it would be 00001.jpg to flam3.

The correction is done here:
 https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L271

**Comment by lordastley** [comment]
Oops, forgot to keep the primary issue in when I edited the initial bug report.
The primary issue is that the frames being rendered are 000-004.jpg but the frames that are being requested for upload are 001-005.jpg. 

005.jpg doesn't exist and is not being uploaded.

**Comment by kochd** [comment]
Confusing...
I dont seam to have a working GPU renderer right now so i can not evaluate on this.

If you change:
https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L278

to
```ruby
  frames = ((begin_frame.to_i-1)..(end_frame.to_i-1)).map{ |i| "#{@frame_dir}/#{concat_name}/#{"%04d" % i.to_s}.jpg" }
```

adding the offset to begin_frame and end_frame it would work as you intend. 

However checking the server's logs i see this:
```
Jun 22 05:30:20 triple6.org puma[611]: I, [2020-06-22T05:30:20.300804 #1116]  INFO -- highdef: requested work: {"sequence":"electricsheep.244.00520.04286_electricsheep.244.00520.04286","begin":506,"end":510}
Jun 22 05:31:17 triple6.org puma[608]: I, [2020-06-22T05:31:17.117432 #1112]  INFO -- highdef: submitted electricsheep.244.00520.04286_electricsheep.244.00520.04286 frame #506
Jun 22 05:31:32 triple6.org puma[609]: I, [2020-06-22T05:31:32.839930 #30812]  INFO -- highdef: submitted electricsheep.244.00520.04286_electricsheep.244.00520.04286 frame #507
Jun 22 05:31:50 triple6.org puma[609]: I, [2020-06-22T05:31:50.310252 #30812]  INFO -- highdef: submitted electricsheep.244.00520.04286_electricsheep.244.00520.04286 frame #508
Jun 22 05:32:06 triple6.org puma[609]: I, [2020-06-22T05:32:06.649445 #30812]  INFO -- highdef: submitted electricsheep.244.00520.04286_electricsheep.244.00520.04286 frame #509
Jun 22 05:32:22 triple6.org puma[609]: I, [2020-06-22T05:32:22.027993 #30812]  INFO -- highdef: submitted electricsheep.244.00520.04286_electricsheep.244.00520.04286 frame #510
```

No missing frames for @highdefractal. He seams to experience a different behavior than you. Question is: WHY?

**Comment by kochd** [comment]
@highdefractal can you clarify anyhow? e.g: Whats your fractorium version?

We are definitely missing the offset here https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L278 as a work_set of 1-4 would result in:
* Rendering 0-3 (https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L271)
* Uploading 1-4 (https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L278)

**Comment by lordastley** [comment]
I don't know ruby, but it seems like if the server is issuing 1-indexed frame ranges, and fractorium is rendering and outputting 0-indexed frame ranges, the fix for uploading would be to change the map to associate frame N with jpeg filename N-1.jpg, going from:
```
  frames = ((begin_frame.to_i)..(end_frame.to_i)).map{ |i| "#{@frame_dir}/#{concat_name}/#{"%04d" % i.to_s}.jpg" }
```
to
```
  frames = ((begin_frame.to_i)..(end_frame.to_i)).map{ |i| "#{@frame_dir}/#{concat_name}/#{"%04d" % (i-1).to_s}.jpg" }
```
However, I suspect this change would visibly break in-progress renders, and create visible seams at the edges between new renders and old renders.

That said, after reading the documentation (http://fractorium.com/?article=emberanimate), it looks like emberanimate should _actually_ be rendering 6 frames if `begin_frame=1` & `end_frame=5` since the emberanimate arguments include:
`          "--begin=#{(begin_frame-1)}",          "--end=#{(end_frame)}", `.
I would expect that emberanimate invocation to yield 000-005.jpg

**Comment by kochd** [comment]
I think the --end frame isn't actually rendered.
And according to your output this is the case:
```
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
```

5x iterating, 5x filtering.
I'll fix my opencl and dig into this. I also think i can also correct the behavior without breaking visual compatibility with older versions.

**Comment by lordastley** [comment]
It looks like the behavior of the --begin/--end flags for emberanimate changed on 2020-03-08 in https://bitbucket.org/mfeemster/fractorium/commits/efa9dc072db18929ca95ab6d5c75b1ac1ac60625

**Comment by kochd** [comment]
As far as i understand this commit only affects using the --frame option:

```c++
if (opt.Frame())
```

it changed how opt.LastFrame and opt.FirstFrame where derived from opt.Frame

**Comment by lordastley** [comment]
You are correct, I missed the parent conditional in the diff.

**Comment by kochd** [comment]
Fixed in: https://github.com/kochd/electricsheep-hd-client/releases/tag/20200622
Any client version before this release is now blocked from contributing with a notification that they need to update.

**Comment by highdefractal** [comment]
> 
> 
> @highdefractal can you clarify anyhow? e.g: Whats your fractorium version?
> 
> We are definitely missing the offset here https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L278 as a work_set of 1-4 would result in:
> 
>     * Rendering 0-3 (https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L271)
> 
>     * Uploading 1-4 (https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L278)

I have been using Fractorium 1.0.0.16. I'm not sure if it was this same exact issue I was seeing but if not it was very similar

**Comment by kochd** [comment]
I had 1.0.0.17 laying around:

* 1.0.0.17 renders Frame 1 as 0001.jpg
* 1.0.0.20 renders Frame 1 as 0000.jpg

-.- this definitely breaks visual compatibility. I'll have to implement a version check of 'good' fractorium versions.

**Comment by highdefractal** [comment]
It's worth mentioning that it appears that upgrading to Fractorium 1.0.0.20 is needed for a Windows box with the latest ESHD release. I was getting no such file or directory for some but not all of the rendered .jpg frames. Unfortunately I didn't grab a screenshot before updating Fractorium but upgrading seems to have solved that issue.

**Comment by highdefractal** [comment]
> 
> 
> I had 1.0.0.17 laying around:
> 
>     * 1.0.0.17 renders Frame 1 as 0001.jpg
> 
>     * 1.0.0.20 renders Frame 1 as 0000.jpg
> 
> 
> -.- this definitely breaks visual compatibility. I'll have to implement a version check for 'good' fractorium versions.

It's builds 1.0.0.19 or higher that have the issue mentioned above. Adding a note to use Fractorium build 1.0.0.20 in the GitHub getting started and the release link if using GPU computing might be helpful...that might be confusing to some though.
