### ISSUE TITLE
Im not receiving email to activate API_KEY

### ISSUE THREAD

**Issue by SpotBR** [kochd/electricsheep-hd-client#58]
Im spotdev@hotmail.com

I would like to help to render...

**Comment by kochd** [comment]
Yup.
```
    SMTP error from remote mail server after MAIL FROM:<electricsheep@triple6.org> SIZE=1900:
    host hotmail-com.olc.protection.outlook.com [104.47.17.97]:
    550 5.7.1 Unfortunately, messages from [84.38.66.197] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3150). 
```

You may want to get a postman that is not making a choice about what you need to read and what not :)

**Comment by SpotBR** [comment]
I tried gmail too. bigarismo@gmail.com

Can you activate my api key spotdev@hotmail.com for GPU mannualy?

**Comment by SpotBR** [comment]
Im using YOPMAIL and it worked well...

**Comment by kochd** [comment]
For gmail check your spam as they always deliver. Mail was accepted 07:42:27 CEST
