### ISSUE TITLE
How can i buy sheeps?

### ISSUE THREAD

**Issue by SpotBR** [kochd/electricsheep-hd-client#60]
How can i buy sheeps? Can we negotiate?

**Comment by kochd** [comment]
<code>
Once your daemon is rendering frames you will gain so called credits for every frame you have rendered. Your daemon will then start to "buy" completed sequences using your gained credits and download them to $BASE_DIR/branches/$CURRENT_BRANCH/movies
</code>

There is no way to really buy sheep with real money and there will never be. Contribute computation, earn results.

**Comment by SpotBR** [comment]
Its ok, i know about contribute because im trusted submitter.
