### ISSUE TITLE
How can i remove a blank sheep?

### ISSUE THREAD

**Issue by SpotBR** [kochd/electricsheep-hd-client#61]
How can i remove a blank sheep?

**SheepName:** electricsheep.244.00003.08366_electricsheep.244.00003.08366.webm
**Sheep preview:** https://imgur.com/soet46z.png

**Comment by SpotBR** [comment]
I downloaded it 3x. Can i receive my credits back?

**Comment by kochd** [comment]
* No there is no refund
* You can not remove them as it would break the sequence. 
* You can try to create a empty file with same name but that might break mpv

This is on the roadmap:
>Handle replacement of bad flames when they are already rendered

For flames you don't like and are not too old you can use the voting system on the website once your trust is high enough. Flames that are voted down will not be used in the future.
