### ISSUE TITLE
Handling Bad Sheeps That are Already Rendered

### ISSUE THREAD

**Issue by ZacMonkeys** [kochd/electricsheep-hd-client#62]
Hi there, I've just discovered this project and I'm absolutely thrilled that I have. I have been a fan of the Electric Sheep project for over 15 years, and this inception of it is finally what I have always been wanting, HD Sheep! I've been rendering frames like mad the last few days, got two PC running both GPU and CPU most of the time. Doing my bit haha =)

The only thing which is a bit annoying (which you already have listed as an issue) are the bad renders of the sheep, with random bad frames etc. 

I'm not a programmer so unfortunately I can't offer my services in that sense, but I would be happy provide my time by going through sheep I have and create a list of filenames of badly rendered sheep, if that is of any use. Perhaps they could then be put "back into the rendering pool"so to speak to be re-rendered?

**Comment by kochd** [comment]
Are you talking about these flames?:
![grafik](https://user-images.githubusercontent.com/1825660/97690917-f2c33880-1a9d-11eb-92ad-b2a588a31ada.png)

The problem with these flames is not that they are rendered falsely. In fact they are rendered correctly but the source flame file is just an ugly sheep. We have some of them in the flock and the only thing we can do about it is to vote them down so their genomes get wiped from the pool and will never be seen again.

On the roadmap there are already two points which would mitigate or even fix this problem:
- Non linear mutation paths
- Handle replacement of bad flames when they are already rendered

Problem is: I am the only one in the community who could do this as there is now team but just me.

**Comment by ZacMonkeys** [comment]
Wow such a quick reply!

No i'm talking about the frames that appear to have a few random frames in
them that don't align with the smooth motion of the rest of the sheep
sequence. I actually don't mind those grey ones too much haha.

For example one that I obtained recently has the filename
"electricsheep.244.00085.13090_electricsheep.244.00085.13090", about 6
seconds in it has a random almost entirely pink frame that flashes up
during the sequence.

There are many others which I've found like this, maybe one in 20 or so
that I have obtained so far. I could like more for you if you'd find it
helpful? Like I said I wish I could offer coding assistance but alas my
coding skills are close to nil..

Maybe I'm being too picky, but when I'm admiring the beauty of the
screensaver in all it's glory these random glitches take me out of the
experience =P

Thanks again for your work on this project, I love it =)

Zac

**Comment by kochd** [comment]
This might be related to:
https://github.com/kochd/electricsheep-hd-client/issues/52

There is a mechanism where you validate the work of others by doing the same work they already did and comparing the result. If your results get blamed to much by others you will get banned. The system protects itself. However as not every frame is validated as this would waste a lot computation power there is a chance that someone was able to submit errors.

Based on the computation power of the community i might decide to raise the validation rate in the future so this can happen less and people get banned faster.

**Comment by ZacMonkeys** [comment]
That makes a lot of sense. But still the problem of the existing bad sheep
remains, doesn't it?

When the work of others is validated and a users work is found to be bad,
do the "bad sheep"get flagged to be deleted or re-rendered? Or is that
essentially what this point seeks to accomplish?

   - Handle replacement of bad flames when they are already rendered

**Comment by kochd** [comment]
Currently: If A says this sheep by B is bad and A has more trust then B it is replaced with the frame that A did.
But as is said this is not done for every frame. 

What
   - Handle replacement of bad flames when they are already rendered

is aiming is for is to replace the once that are just ugly.

**Comment by kochd** [comment]
There was also this problem https://github.com/kochd/electricsheep-hd-client/issues/37

**Comment by kochd** [comment]
Which resulted in this: https://bitbucket.org/mfeemster/fractorium/issues/27/flam3-compatibility-after-1008

**Comment by ZacMonkeys** [comment]
Yes, this is exactly the stuff that I am talking about.

So this issue is now resolved in sheeps (or do we call them flames now?)
that are being rendered moving forward. It's just some of the old GPU
rendered ones that have these glitches in them as a result?

If that's the case then can we just re-render all the GPU flames that were
rendered while this issue existed? Probably a lot of extra rendering work,
but if it fixes these glitches in these old flames then i think it would be
worth it. I'm happy to dedicate my machine to rendering for quite some time
=)

**Comment by kochd** [comment]
Terminology: A flame (https://flam3.com/) is a XML file or the the algorithm used to produce as sheep as a result.

 As we are not quite sure about the exact period when this happened and there is no mechanism to replace the webm files on the clients we decided against rerendering.

**Comment by ZacMonkeys** [comment]
Ok fair enough. So what would be the best way to try to get a "glitch free
flock" so to speak?

Just delete the ones I find from my own HD?

**Comment by kochd** [comment]
Sadly there is no way to clean this up. If you delete them you get them back from the server with your next download.

**Comment by ZacMonkeys** [comment]
Ahh that's a shame!

I know you say you've already decided against re-rendering and my opinion
counts for next to nothing, but I would suggest to reconsider.

In the long run I think the sunk cost of re-rendering those glitchy sheep
would be outweighed by the value of a glitch free flock. GPUs are getting
next level, AMD just announced their RTX 3090 killer which is ridiculously
powerful for the price!

We would be able to re-render in a fraction of the time with just a few
beasty GPUs =)

In the meantime, is there any way to point the "Play" to a different
folder, perhaps? One could create a specific folder to hold only the "good"
sheep? One could put preferred sheep in there to create a sort of "custom"
flock as well.

**Comment by kochd** [comment]
How this is done is mentioned in the first line of play

https://github.com/kochd/electricsheep-hd-client/blob/master/play#L1

You just call 
```./play my_special_season```
and it will play that branch

**Comment by kochd** [comment]
Create a directory with *.webm files an use -d to point to that directory

**Comment by kochd** [comment]
If you create a list of sequences that need to be re-rendered i can mark them as undone.
I need them like this:
electricsheep.244.00897.04299_electricsheep.244.00897.04299

**Comment by ZacMonkeys** [comment]
Ok, great I will get started working on that! Thank you, I think it will be
well worth it in the end =)

**Comment by ZacMonkeys** [comment]
Here's a list of ones that I found in about an hour this morning. One thing
I have noticed is that in most of these, it's actually just the first one
of two frames that are bad. There are a few where there are frames in the
middle which are bad, but in a lot of them it seems that the first frame
will be a sort of "misaligned / scattered" version of the rest of the
sheep, and then after that it seems to be fine. I feel like this is
possibly due to a different issue?

I don't know, maybe take a look at these and see what you think?

electricsheep.244.00001.03936_electricsheep.244.00001.03936
electricsheep.244.00006.03863_electricsheep.244.00007.12860
electricsheep.244.00010.07110_electricsheep.244.00010.07110
electricsheep.244.00010.07110_electricsheep.244.00011.10201
electricsheep.244.00015.07578_electricsheep.244.00016.08343
electricsheep.244.00023.13048_electricsheep.244.00024.08335
electricsheep.244.00026.07216_electricsheep.244.00027.00996
electricsheep.244.00027.00996_electricsheep.244.00028.11440
electricsheep.244.00032.01766_electricsheep.244.00033.00410

**Comment by ZacMonkeys** [comment]
Some more. Again mostly these have a few frames at the very start that are
bad. I am finding less as I move through the later numbers in the list.

electricsheep.244.00036.00446_electricsheep.244.00037.10922
electricsheep.244.00041.11238_electricsheep.244.00042.11378
electricsheep.244.00060.01719_electricsheep.244.00061.07918

  I've nearly worked my way through all of the 4K sheep on my hard drive so
far. I'll keep going through more as I obtain more from the server

**Comment by kochd** [comment]
They have been completed by now. They are on hold for 48 hours before being rendered into webm

**Comment by ZacMonkeys** [comment]
Did some more sheep reviewing this morning, found a whole section that has
bad frames in virtually every sheep. I would suggest to add these to the
list to be re-rendered:

I have noticed in these, that most of the 'bad frames' are just slightly
misaligned with the rest. Some of the frames are grossly incorrect (almot a
mirror image of the previous frame) but many are just slightly misaligned,
but it still creates a very noticeable glitch.

electricsheep.244.00094.03220_electricsheep.244.00095.05828
electricsheep.244.00095.05828_electricsheep.244.00095.05828
electricsheep.244.00095.05828_electricsheep.244.00096.12654
electricsheep.244.00096.12654_electricsheep.244.00096.12654
electricsheep.244.00096.12654_electricsheep.244.00097.07936
electricsheep.244.00097.07936_electricsheep.244.00097.07936
electricsheep.244.00097.07936_electricsheep.244.00098.01353
electricsheep.244.00098.01353_electricsheep.244.00098.01353
electricsheep.244.00098.01353_electricsheep.244.00099.02736
electricsheep.244.00099.02736_electricsheep.244.00099.02736
electricsheep.244.00099.02736_electricsheep.244.00100.07905
electricsheep.244.00100.07905_electricsheep.244.00100.07905
electricsheep.244.00100.07905_electricsheep.244.00101.11554
electricsheep.244.00101.11554_electricsheep.244.00101.11554
electricsheep.244.00101.11554_electricsheep.244.00102.11220
electricsheep.244.00102.11220_electricsheep.244.00102.11220
electricsheep.244.00102.11220_electricsheep.244.00103.03034
electricsheep.244.00103.03034_electricsheep.244.00103.03034
electricsheep.244.00103.03034_electricsheep.244.00104.05569
electricsheep.244.00104.05569_electricsheep.244.00104.05569
electricsheep.244.00104.05569_electricsheep.244.00105.02963
electricsheep.244.00105.02963_electricsheep.244.00105.02963
electricsheep.244.00105.02963_electricsheep.244.00106.05767
electricsheep.244.00106.05767_electricsheep.244.00106.05767
electricsheep.244.00106.05767_electricsheep.244.00107.06188
electricsheep.244.00107.06188_electricsheep.244.00107.06188

**Comment by kochd** [comment]
I've marked them
