### ISSUE TITLE
Corrupted webm files (3 bytes)

### ISSUE THREAD

**Issue by daggerdragon** [kochd/electricsheep-hd-client#65]
I love this project.  The GPU videos in particular are stunning (so short, though!).  I let the daemons run overnight and sometimes end up disappointed when I wake up to some broken/invalid/bad .webm videos :(  Can we have a way (perhaps via the website?) to report and/or redownload (or at least get our credits back) for bad .webms?

Is there a better way to report these bad .webms?

My computer's specs:
* Windows 10 Pro x64 version 20H2
* AMD Ryzen 7 2700X
* AMD Radeon RX 480

Here's a list of the bad ones I've gotten so far:

### Branch G244_W1920_H1080_Q1024_K1C1DF3M
All of these say that they're only 3 bytes in size which indicates that they didn't download properly (or are corrupted?):
* electricsheep.244.00594.13201_electricsheep.244.00594.13201.webm
* electricsheep.244.00594.13201_electricsheep.244.00595.12485.webm
* electricsheep.244.00609.13404_electricsheep.244.00609.13404.webm
* electricsheep.244.00610.04951_electricsheep.244.00611.03205.webm
* electricsheep.244.00611.03205_electricsheep.244.00611.03205.webm
* electricsheep.244.00624.11716_electricsheep.244.00624.11716.webm

![ElectricSheepHD_CPU](https://user-images.githubusercontent.com/16218634/99302786-d6edbf80-281d-11eb-84ff-039d2681c982.jpg)

### Branch G244_W3840_H2160_Q1024_KFVGM5cUGPU
This one didn't download properly, says it's only 3 bytes in size:
* electricsheep.244.00010.07110_electricsheep.244.00010.07110.webm

These two show the whole video is static snow on purple background:
* electricsheep.244.00003.08366_electricsheep.244.00003.08366.webm
* electricsheep.244.00009.11125_electricsheep.244.00009.11125.webm

![ElectricSheepHD_GPU](https://user-images.githubusercontent.com/16218634/99303118-64311400-281e-11eb-9c3e-d81b3285c63f.jpg)

Example of the "static snow on purple background" videos (it's very subtle and hard to see from a static image, but if you zoom in with VLC while playing the video, it's quite apparent):

![ElectricSheepHD_GPU-Snow](https://user-images.githubusercontent.com/16218634/99303391-d570c700-281e-11eb-84e4-b8cd8289350d.jpg)

----

Thank you for your attention to this issue.  Let me know if you need any further information!

**Comment by kochd** [comment]
The only issue here is the "3 bytes" part.

* Ugly sheeps are just ugly. 
* Vote them down
* Create better ones and upload them

3 bytes issue:
This was never reported before so this is somewhat strange.
My client has downloaded 1540 webms from G244_W1920_H1080_Q1024_K1C1DF3M an none of them is broken.
The source files on the server are fine as well
Looking a the daemon (https://github.com/kochd/electricsheep-hd-client/blob/4608132f359877ff455162cbef7a2f66506912eb/daemon#L331) the should not have been renamed if download failed. 

If you delete one of them your next download will be that particular file again. Can you check if you get any errors in that stage?

**Comment by daggerdragon** [comment]
I deleted `\branches\G244_W1920_H1080_Q1024_K1C1DF3M\electricsheep.244.00594.13201_electricsheep.244.00594.13201.webm` and kept an eye on the daemon for a new download.  Next file was indeed `electricsheep.244.00594.13201_electricsheep.244.00594.13201.webm` and THAT one shows up properly with a pretty thumbnail and 48.7 MB.

![RedownloadedSheep](https://user-images.githubusercontent.com/16218634/99577410-4d6af880-29a9-11eb-8d6c-188f49ba4238.jpg)

---

I don't speak Ruby but it looks like from the control structure of the code you pasted that the file will be renamed regardless of whether it is properly downloaded or not - I see no checks, it just assumes the file downloads properly.

Perhaps consider including a checksum string of some sort for the incomplete filename and when the control loop ends, check against the "downloaded" file and if the checksum matches, THEN do the rename (and remove the checksum string from the filename).

Good luck!  :)

**Comment by kochd** [comment]
> I don't speak Ruby but it looks like from the control structure of the code snippet you pasted that the file will be renamed regardless of whether it is properly downloaded or not; I see no parity/sanity checks, it appears to assume the file downloads properly.

No that not correct. Ruby will raise an exception if anything goes wrong that isn't specifically rescued.
For example if the connection would drop Ruby would raise
```ruby
Errno::ECONNRESET
```

and nothing is rescued here so if anything goes abnormal the #.rename would never be reached
