### ISSUE TITLE
Regular crashes when rendering on an Apple MBP M1 / silicon

### ISSUE THREAD

**Issue by NewAlexandria** [kochd/electricsheep-hd-client#66]
Running on an M1 recently.  I experience two big issues

* the daemon crashes regularly (every 20 min or so?)
* the daemon sometimes doesn't acquire a new sheep to render - sometimes for an hour or so.

Can confirm that I'm not running a firewall.  
When the daemon crashes, the error is `76440 illegal hardware instruction`.

I'm not really sure where to go next with debugging this, but glad to tool around if given direction.  Can get on IRC

**Comment by NewAlexandria** [comment]
I think the latter no-sheep issue is perhaps from P2P throttling, when I kept cancelling and trying to re-start the process due to crashes

**Comment by kochd** [comment]
Hello there,

* What is the last thing logged when either of those two things happens? 
* Are we talking GPU or CPU here?

**Comment by NewAlexandria** [comment]
Thanks, I hadn't remembered to look in the console logs.  [Here is one.](https://gist.github.com/NewAlexandria/2b2cc13c389838f77e40ccdd75270b37)  

I'm using CPU rendering (since I didn't flag GPU, and I don't presume `flam3` knows how to recognize the M1 as a GPU (?)

**Comment by kochd** [comment]
Okay my guess is your installed ruby version (most likely preinstalled by apple) has some issues with the arm-64 set.
Can you give me the output of the daemon itself so we can determine on which actions ruby crashed?
Is it downloading, uploading, solving pow, etc.?

**Comment by NewAlexandria** [comment]
my guess is that it's uploading, or something at the end of rendering. 

```
[07:40:20] INFO: Rendering... electricsheep.244.01035.03027_electricsheep.244.01036.02965 Frame 591
[07:42:09] INFO: Uploading... electricsheep.244.01035.03027_electricsheep.244.01036.02965 Frame 591
[07:42:16] INFO: Active season: G244_W1920_H1080_Q1024_K1C1DF3M
[07:42:16] INFO: Cleaning up animated genomes...
[07:42:16] INFO: Updating DHT
[07:42:18] INFO: Requesting new work...
[07:42:18] INFO: Solving PoW...
[07:42:20] INFO: Solved after 3 seconds
[07:42:23] INFO: Rendering... electricsheep.244.01035.03027_electricsheep.244.01036.02965 Frame 592
[1]    25049 illegal hardware instruction  ./daemon -k --np --debug
```

**Comment by NewAlexandria** [comment]
I forgot to respond to the `ruby` comment. 

I'm not running the system native ruby.  I'm built one via `rvm`.    `asdf` wraps `rvm`.

```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
$ which ruby
/Users/zak/.asdf/shims/ruby
```

I can build/run any one you'd like to confirm

**Comment by NewAlexandria** [comment]
I tried running using the system-native ruby, thinking that the Apple team would have build a version without any arm-64 / M1 issues.  It still crashes.  I assume it's not arm

```
ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
```

**Comment by kochd** [comment]
As "x86_64" implies: it's not. ARM does not use the x86 instruction set. However there is no reason why ruby can't be build for native arm64 instructions. Looks like there is some instructions translation going on.

This might help solve your issues:
https://www.driftingruby.com/episodes/a-rubyist-s-apple-m1-review

However the
> illegal hardware instruction

error imho comes from the flam3 binary. (https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L226)
It may needs to be prefixed with the "arch -x86_64" wrapper command?
