### ISSUE TITLE
Currently on downtime

### ISSUE THREAD

**Issue by EricChiz** [kochd/electricsheep-hd-client#69]
On 2021-02-23 at approximately 12:21:50 UTC, everything on the triple6.org server stopped responding, whereas 30 seconds previous it had been operating as expected. Is there an ETA for when the servers will be functional again, and if there has been significant data loss from this event?

**Comment by kochd** [comment]
This is a planed event to prevent data loss for an upcoming update over the cause of this weekend.
I plan to be completely finished by Monday (GMT+1) but expect further service down times during this process
