### ISSUE TITLE
Server response 901: untrusted

### ISSUE THREAD

**Issue by perezidentkanye** [kochd/electricsheep-hd-client#72]
i keep getting this error after entering my apikey after leaving the program running overnight

**Comment by kochd** [comment]
Are you perez.ja98 ?

**Comment by perezidentkanye** [comment]
yes

**Comment by kochd** [comment]
This is kinda intended:
You where rendering alone in the cpu branch. 
As a new submitter someone needs to verify that your work is trustworthy so everything you submit first gets queued for verification.
By now your submissions are getting verified and you've reached the 1 star level which enables you to submit without the need for pre-verification.
So this should be solved as long as the network keeps being fine with your submissions.

**Comment by perezidentkanye** [comment]
oh okay thank you, I wasn't sure because everything seemed to be working
fine at first until it stopped the next morning so I wanted to make sure I
didn't fuck anything up haha thanks again!

**Comment by kochd** [comment]
no problem, your welcome.
This wouldn't have happened if someone was verifying while you where submitting but my renderer crashed unnoticed yesterday.
