### ISSUE TITLE
question: what is the 'proof of work' for?

### ISSUE THREAD

**Issue by symgryph** [kochd/electricsheep-hd-client#75]
I am running on various systems. Is the proof of work for preventing spamming or some kind of crypto mining?

**Comment by kochd** [comment]
> The concept was invented by Cynthia Dwork and Moni Naor in 1993 as a way to deter denial-of-service attacks and other service abuses such as spam on a network by requiring some work from a service requester, usually meaning processing time by a computer.

https://en.wikipedia.org/wiki/Proof_of_work

And that's basically the whole point in this project as well.

**Comment by kochd** [comment]
PoW gets easier once you've reached three stars trust level by the way.

**Comment by symgryph** [comment]
Thank you for the explanation.
