### ISSUE TITLE
Migration away from self-signed certificate?

### ISSUE THREAD

**Issue by Forbo** [kochd/electricsheep-hd-client#78]
Hi there! Thank you so much for this project, I absolutely love it.  It's been nice getting back into Electric Sheep after all these years. Hoping to set up a donation here in the next week or so.

Anyway, are there any plans to move away from the self-signed certificate that's currently in use on sheeps.triple6.org, possibly to something like Let's Encrypt? The self-signed cert is generating a lot of noise in my IDS logs.

**Comment by Forbo** [comment]
I just noticed this was brought up in https://github.com/kochd/electricsheep-hd-client/issues/34

Should I close this issue, since that one is still open?

**Comment by kochd** [comment]
As mentioned in #34 the cert is shipped with the client to ensure everyone only accepts input from the correct server.
As Let's Encrypt certs expire after 3 months they are not an option.
Other than buying a cert from a trusted ca (which will expire within 12 month for revenue reasons) I see no option that would not weaken the security of the client.
