### ISSUE TITLE
Not an issue: Just a query for knowledge.

### ISSUE THREAD

**Issue by Aquaritek** [kochd/electricsheep-hd-client#82]
Hey Kochd,

I've been researching electric sheep quite a bit over the last couple of weeks. I was wondering just as a fellow lover of this technology - if you would be willing to share some insights into how you either gained access or created the "animated genomes" that are used to produce these videos.

It's almost a baren wasteland out there in terms of how to achieve this from flat genomes (single flames). I don't know why I'm having so much trouble finding the information to learn this.

With peace, Aqua.

**Comment by kochd** [comment]
You need to things: Sequence and Template.
Ill just paste some snippets and you point to the things you struggle with:

SEQUENCE:
This one is easy it puts 2 genomes into a single XML wrapped into a `<flames name="Batch">` block
``` ruby
  def self.concat_genomes(genome1, genome2)

    fail "Genome 1 does not exist #{GENOME_DIR}/#{genome1}" unless File.exist?("#{GENOME_DIR}/#{genome1}")
    fail "Genome 2 does not exist #{GENOME_DIR}/#{genome2}" unless File.exist?("#{GENOME_DIR}/#{genome2}")

    temp_genome = Tempfile.new("electricsheep-hd")
    temp_genome.write "<flames name=\"Batch\">\n"
    temp_genome.write File.read("#{GENOME_DIR}/#{genome1}").split("<flame name=").first(2).join("<flame name=").gsub(/^<(pick|\/pick).*$/, '')
    temp_genome.write File.read("#{GENOME_DIR}/#{genome2}").split("<flame name=").first(2).join("<flame name=").gsub(/^<(pick|\/pick).*$/, '')
    temp_genome.write "</flames>\n"
    temp_genome.rewind
    temp_genome.fsync
    return temp_genome
  end
```
TEMPLATE:
Next we generate a template (https://github.com/scottdraves/flam3/blob/ba790dfc3e09a9dd45a19e698dd4c244ed1e429e/README.txt#L64). It contains the parameters how this animation should be rendered. resolution, quality and so on:
``` ruby
    # Merge old and new flames into a single file to make the animation from
    ## Thats the genome from #concat_genomes
    temp_genome = Season.concat_genomes(genome1, genome2)


    # Create a new flame file with enough frames to loop
    anim_template = File.open("/tmp/anim_template_#{SecureRandom.hex}.flame","w")
    anim_template.write "<flame supersample=\"2\" temporal_samples=\"#{temporal_samples}\" quality=\"#{quality}\" size=\"#{width} #{height}\" />\n"
    anim_template.fsync
```
USE THEM:
Next we use the flam3 executable to generate a *.flame file which contains all instructions needed to build a animation from it. These are the files that the client of this project will download. 
``` ruby
    LOGGER.info("Generating Work") {"#{gid1}_#{gid2}"}
    LOGGER.info("Generating Work") {"flam3-genome > #{animated_genome_dir.expand_path}/#{gid1}_#{gid2}.flame"}
    result = `template='#{File.expand_path(anim_template)}' sequence='#{File.expand_path(temp_genome)}' nframes='#{nframes.to_s}' verbose='1' flam3-genome > #{animated_genome_dir.expand_path}/#{gid1}_#{gid2}.flame`
```
