### ISSUE TITLE
Hash Verification Failed

### ISSUE THREAD

**Issue by Rekrith** [kochd/electricsheep-hd-client#83]
So, I'm new to contributing - just today - I've mostly been rendering via GPU. However, after a couple of hours I decided to try and see if I could play any sheep but found that it still said I had 0. I wondered if it was possible that contributing via GPU wasn't giving 'normal' credits or something, so I tried running the normal Daemon off my CPU instead.

I found, slightly to my dismay, that whenever I run the non-GPU Daemon I run into this one error every time my system tries to upload a frame:
`ERROR: Error in upload: hash verification failed`
The Daemon runs GPU mode without a problem.

Any thoughts? Would a full render log help diagnose the issue? Thank you for reading!

**Comment by kochd** [comment]
> ERROR: Error in upload: hash verification failed

This one is fixed now.

On your downloading problem:
Can you tell me the first 4-5 characters of your mail address, so I can identify your account?

**Comment by kochd** [comment]
I think you've downloaded 4 parts from the GPU branch by now.
"play" plays the last branch you **started** rendering in.

 So if you launch CPU rendering and then start play there are no sheeps.

**Comment by Rekrith** [comment]
So sorry not to get back to you sooner! I forgot to come back to the thread. If you haven't already seen it, it's CRAFT - though your second comment makes it sound like you found it? For downloads, I'm not sure what the issue was but you're entirely right in that it went away soon enough. If that was something from your end, thank you!
Duly noted on the GPU/CPU branch for future reference.

Thanks, at any rate - really appreciated!
