### ISSUE TITLE
SQL Indexing

### ISSUE THREAD

**Issue by beadon** [kochd/electricsheep-hd-client#90]
IT sounds like the hardware is a little low-powered for these kind of tasks - what does the backend database look like ?  It sounds like a time series database might be more appropriate ?

**Comment by kochd** [comment]
Postgresql. This is not the type of use case for a TSDB is it?

**Comment by beadon** [comment]
Only if the data coming is in specifically ordered by time.  I don't know what is on the tables though.  It sounds like this might be tracking the frames that are being sequenced and the state of each one ?
