### ISSUE TITLE
error on infrastructure?

### ISSUE THREAD

**Issue by beadon-SAT** [kochd/electricsheep-hd-client#91]
[03:17:53] WARN: Server response 502: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.25 (Debian) Server at sheeps.triple6.org Port 443</address>
</body></html>

[03:17:54] WARN: Server response 999: PoW
[03:17:54] ERROR: 767: unexpected token at 'PoW'

**Comment by kochd** [comment]
This happens for ~2% of the request the server handles due to its load.

**Comment by beadon-SAT** [comment]
So - should we devise a better system to handle the load ?
