### ISSUE TITLE
Crash on Upload

### ISSUE THREAD

**Issue by beadon** [kochd/electricsheep-hd-client#93]
Unclear what happened here - looks like there was an end of file error that was uncaught.  Thoughts on how to fix ?

[18:08:32] INFO: Uploading... electricsheep.244.01906.11868_electricsheep.244.01906.11868 Frame 294
[18:08:38] INFO: Active season: G244_W1920_H1080_Q1024_K1C1DF3M
[18:08:38] INFO: Cleaning up animated genomes...
[18:08:38] INFO: Updating DHT
[18:08:38] INFO: Requesting new work...
[18:08:38] INFO: Solving PoW...
[18:08:41] INFO: Solved after 3 seconds
[18:08:48] INFO: Rendering... electricsheep.244.01910.00939_electricsheep.244.01911.10489 Frame 463
chaos: 100.0%  took: 268 seconds
filtering...writing C:/Program Files (x86)/Electric Sheep HD/branches/G244_W1920_H1080_Q1024_K1C1DF3M/frames/electricsheep.244.01910.00939_electricsheep.244.01911.10489/00463.jpg...done.
[18:13:25] INFO: Uploading... electricsheep.244.01910.00939_electricsheep.244.01911.10489 Frame 463
Traceback (most recent call last):
        23: from daemon:353:in `<main>'
        22: from daemon:353:in `loop'
        21: from daemon:397:in `block in <main>'
        20: from daemon:220:in `request_work'
        19: from daemon:220:in `each'
        18: from daemon:229:in `block in request_work'
        17: from daemon:306:in `upload_frame'
        16: from daemon:306:in `open'
        15: from daemon:315:in `block in upload_frame'
        14: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http.rb:1470:in `request'
        13: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http.rb:920:in `start'
        12: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
        11: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http.rb:1479:in `request'
        10: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http.rb:1517:in `transport_request'
         9: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:166:in `reading_body'
         8: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:229:in `body'
         7: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:204:in `read_body'
         6: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:283:in `read_body_0'
         5: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:278:in `inflater'
         4: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:285:in `block in read_body_0'
         3: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/http/response.rb:315:in `read_chunked'
         2: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
         1: from C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
C:/Program Files (x86)/Electric Sheep HD/contrib/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)

**Comment by kochd** [comment]
Never seen this myself.
Connection loss? The EOF is related to the response body not a file.
