### ISSUE TITLE
Uploading frames sometimes fails. Daemon never retries

### ISSUE THREAD

**Issue by LucasUP** [kochd/electricsheep-hd-client#98]
The daemon is sometimes failing to upload and prints this error message. The server is probably just taxed, but the problem is it doesn't retry the upload process.
![cmd_2022_07_06_21-19-613](https://user-images.githubusercontent.com/3720253/177691268-825fb979-f394-4450-99a5-ecd96add9514.png)

The daemon eventually restarts the process and starts requesting new work, but doesn't seem to actually retry to upload any completed work that failed to upload successfully last time.
![explorer_2022_07_06_21-27-614](https://user-images.githubusercontent.com/3720253/177691274-27f1b37d-078e-4da8-83d6-484ceea23bb1.png)

**Comment by kochd** [comment]
This is known problem. Everything from your issue is answered here: 
https://github.com/kochd/electricsheep-hd-client/issues/84
