### ISSUE TITLE
my api key says untrusted?

### ISSUE THREAD

**Issue by Ghitim** [kochd/electricsheep-hd-client#99]
hi, i was rendering away and suddenly i wasn't and now when i start up it says api key untrusted? did i do something wrong?

**Comment by Ghitim** [comment]
uhhhh, it seems to be back to working now. from reading old threads it seems someone might not have been verifying my renders?

is it cool to run more than one session/deamon?

**Comment by kochd** [comment]
> is it cool to run more than one session/deamon?
That completely fine 

If you are a new user you have to establish trust first. This is done by others verifying that you produce the same renderings as they do. You might get blocked at first if you submitted enough frames for verification. 

If you have any further problems please make sure to provide your username so I can look into it.
